//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoNoHarm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoices
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int accountant_id { get; set; }
        public int order_id { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual orders orders { get; set; }
        public virtual users users { get; set; }
    }
}
