//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoNoHarm.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoNoHarmDB : DbContext
    {
        public DoNoHarmDB()
            : base("name=DoNoHarmDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<employee_services> employee_services { get; set; }
        public virtual DbSet<invoices> invoices { get; set; }
        public virtual DbSet<login_attempts> login_attempts { get; set; }
        public virtual DbSet<order_services> order_services { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<utilizers> utilizers { get; set; }
    }
}
