//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoNoHarm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_services
    {
        public int id { get; set; }
        public int service_id { get; set; }
        public int order_id { get; set; }
        public short status { get; set; }
        public Nullable<int> utilizer_id { get; set; }
        public Nullable<System.DateTime> started_at { get; set; }
        public Nullable<System.DateTime> finished_at { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual services services { get; set; }
        public virtual utilizers utilizers { get; set; }
    }
}
